apiVersion: apps/v1
kind: Deployment
metadata:
        labels:
                app: go-helloworld-2
        name: go-helloworld-2
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: go-helloworld-2
        template:
                metadata:
                        labels:
                                app: go-helloworld-2
                spec:
                        containers:
                                - image: hampen2go/go-helloworld-2:dcec3461824dbd091680396fdc49e0714e1d0f00
                                  name: go-helloworld-2
